// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/e17-themes/BoldNavy.tsx": () => import("../components/mockups/e17-themes/BoldNavy.tsx"),
  "./components/mockups/e17-themes/CleanLight.tsx": () => import("../components/mockups/e17-themes/CleanLight.tsx"),
  "./components/mockups/e17-themes/DarkTech.tsx": () => import("../components/mockups/e17-themes/DarkTech.tsx")
};
